
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086" # InfluxDB HTTP API 포트
      - "8083:8083" # InfluxDB 웹 UI 포트
    environment:
    - INFLUXDB_DB=shield
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=abcde12#
      - INFLUXDB_USER=inspire12
      - INFLUXDB_USER_PASSWORD=abcde12#
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf # 사용자 정의 설정 파일 마운트
    command: influxd -config /etc/influxdb/influxdb.conf
    restart: unless-stopped

  chronograf:
    image: chronograf:1.8
    container_name: chronograf
    ports:
      - "8888:8888" # Chronograf 웹 UI 포트
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - CHRONOGRAF_ADMIN_PASSWORD=${CHRONOGRAF_ADMIN_PASSWORD}
    volumes:
      - chronograf_data:/var/lib/chronograf
    restart: unless-stopped

volumes:
  influxdb_data:
    driver: local
  chronograf_data:
    driver: local