global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-demo-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:8080']
