# docker-compose.yml
version: '3'

services:
  jenkins:
    build:
      context: .
    user: root
    ports:
      - 8180:8080
      - 8181:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock