{
 "title": "sample",
 "time": { "from": "2024-04-30T02:50:40.874Z", "to": "2024-04-30T08:50:40.874Z" },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "일별 유저가 몰렸던 갯수",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select count(user_id) from shield_log_test where JSON_EXTRACT(data, '$.Action') ='login' and created >= subdate(CURRENT_DATE(), 1);"
    }
   ]
  },
  {
   "title": "10분간 트래픽이 몰린 신호등",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select count(user_id) from shield_log_test where JSON_EXTRACT(data, '$.Action') ='login' and created >= now() - INTERVAL 10 MINUTE;"
    }
   ]
  },
  {
   "title": "해외 접속 차단 설정 또는 해제 계정수(비율)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "indicator",
     "rawSql": "select sum(control) as 설정, sum(blocked) as 차단 from indicator.BlockAccess;"
    }
   ]
  },
  {
   "title": "해외 접속 차단 설정 또는 해제 계정수",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "indicator",
     "rawSql": "select date, control, blocked from indicator.BlockAccess order by id desc;"
    }
   ]
  }
 ]
}