# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: mysql
    orgId: 1
    name: mysql
    type: mysql
    url: host.docker.internal:3306
    secureJsonData:
      password: 'abcde12#'
    user: 'root'
    database: 'inspire12'
  - uid: op-mysql
    orgId: 2
    name: mysql
    type: mysql
    url: 172.19.217.124:3306
    secureJsonData:
      password: 'abcde12#'
    user: 'root'
    database: 'shield_log'

