version: "3"
services:
  mongo:
    image: mongo:5.0
    ports:
      - 8317:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=inspire12_api
