services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-clock-panel,grafana-simple-json-datasource,heywesty-trafficlight-panel,sentinelone-dataset-datasource,boazreicher-sierraplot-panel
      - GF_PANELS_ENABLE_ALPHA=true
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
#      - /etc/localtime:/etc/localtime:ro
#      - ~/grafana/config:/Users/inspire12/var/lib/grafana
    user: '472'
    ports:
      - 8030:3000
    restart: always