version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/grafana/config:/Users/inspire12/var/lib/grafana
    user: '472'
    ports:
      - 8030:3000
    restart: always