mage:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.4-debian-10-r41
  pullPolicy: IfNotPresent

architecture: standalone

useStatefulSet: true

## MongoDB(R) Authentication parameters
auth:
  enabled: true
  rootPassword: "abcde12#"
  username: admin
  password: abcde12#
  database: sample

##
persistence:
  enabled: true
  storageClass: "nfs-standard"
  accessModes:
    - ReadWriteOnce
  size: 2Gi

service:
  type: NodePort
  port: 27017
  portName: mongodb