{
 "title": "sample",
 "time": { "from": "2024-04-30T02:50:40.874Z", "to": "2024-04-30T08:50:40.874Z" },
 "panels": [
  {
   "title": "Geo map panel",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "airflow",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`timestamp`) as time_sec,\r\n  `value` as value,\r\n  country_code as metric\r\nFROM worldmap\r\nwhere `timestamp`  >=DATE_FORMAT(CURDATE(), '%Y-%m-%d')\r\n"
    }
   ]
  },
  {
   "title": "Geo map panel",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "airflow",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(`timestamp`) as time_sec,\r\n  `value` as value,\r\n  country_code as metric\r\nFROM worldmap\r\nwhere `timestamp`  >=DATE_FORMAT(CURDATE(), '%Y-%m-%d')\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "airflow",
     "rawSql": "select * from shield_indicator_login order by hour;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select * from shield_log.shield_log_matrix;"
    }
   ]
  },
  {
   "title": "신호등 하루간 userId 확인",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select value from shield_log.shield_indicator_login order by hour desc LIMIT 1;"
    }
   ]
  },
  {
   "title": "해외 접속 차단 설정 또는 해제 계정수(비율)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "indicator",
     "rawSql": "select sum(control) as 설정, sum(blocked) as 차단 from indicator.BlockAccess;"
    }
   ]
  },
  {
   "title": "해외 접속 차단 설정 또는 해제 계정수",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "indicator",
     "rawSql": "select date, control, blocked from indicator.BlockAccess order by id desc;"
    }
   ]
  }
 ]
}